// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-dgVp7dUZ-dj70OZJgEXIh4U4pKrC1I4',
    appId: '1:934689915482:web:8b750e8a33e37e45ff0e63',
    messagingSenderId: '934689915482',
    projectId: 'weqaya-sehat-d2bf3',
    authDomain: 'weqaya-sehat-d2bf3.firebaseapp.com',
    storageBucket: 'weqaya-sehat-d2bf3.appspot.com',
    measurementId: 'G-73Y1SMXF1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr7vQu-GK5wIZSbxHBOKhGTinGsL1owtU',
    appId: '1:934689915482:android:e0fea5615837858eff0e63',
    messagingSenderId: '934689915482',
    projectId: 'weqaya-sehat-d2bf3',
    storageBucket: 'weqaya-sehat-d2bf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC20G-67rsRSlBJuBnKoU_20pRL83jIODk',
    appId: '1:934689915482:ios:b9dbf45c64577c77ff0e63',
    messagingSenderId: '934689915482',
    projectId: 'weqaya-sehat-d2bf3',
    storageBucket: 'weqaya-sehat-d2bf3.appspot.com',
    iosClientId: '934689915482-eve5glm55leij48vonmobhradflkrsk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.weqaya',
  );
}
